// <auto-generated />
using CodeFirst2.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirst2.Migrations
{
    [DbContext(typeof(DatabaseDbContext))]
    [Migration("20200528150234_dataMigration")]
    partial class dataMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirst2.Context.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Budget")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 100000000000000.0,
                            Location = "Midland, MI",
                            Name = "R&D",
                            Type = "Science"
                        },
                        new
                        {
                            Id = 2,
                            Budget = 200000000000000.0,
                            Location = "Dhaka, Bangladesh",
                            Name = "HR",
                            Type = "Administrative"
                        },
                        new
                        {
                            Id = 3,
                            Budget = 53.0,
                            Location = "Party City, USA",
                            Name = "Fun Department",
                            Type = "Administrative"
                        });
                });

            modelBuilder.Entity("CodeFirst2.Context.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "venkman@ghostbusters.co",
                            FirstName = "Peter",
                            LastName = "Venkman"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "ray@ghostbusters.co",
                            FirstName = "Ray",
                            LastName = "Stantz"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "egon@ghostbusters.co",
                            FirstName = "Egon",
                            LastName = "Spengler"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Email = "slimer@ghosts.co",
                            FirstName = "Slimer"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            Email = "dana@nyphil.co",
                            FirstName = "Dana",
                            LastName = "Barrett"
                        });
                });

            modelBuilder.Entity("CodeFirst2.Context.Employee", b =>
                {
                    b.HasOne("CodeFirst2.Context.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
